
server:
  port: 9090

#Below part is not required.

zuul:
  routes:
    orders:
      path: /order-service/**
      url: order-service
    users:
      path: /user-service/**
      url: user-service
    user-authentication:
      path: /user-authentication-service/**
      url: user-authentication-service
    
  